<?php
return [
    'users'=>['max'=>80],
    'projects'=>[
        'max'=>300,
        'max_developers'=>3,
        'max_tester'=>3,
        'min_random_view'=>10,
        'max_random_view'=>40,
        'min_folder_request'=>10,
        'max_folder_request'=>30,
        'min_request'=>30,
        'max_request'=>70,
        'min_folder_requirement'=>20,
        'max_folder_requirement'=>40,
        'min_requirement'=>100,
        'max_requirement'=>200,
        'min_test_suite'=>10,
        'max_test_suite'=>30,
        'min_test_case'=>200,
        'max_test_case'=>400,
        'min_release'=>15,
        'max_release'=>40,
        'min_bug'=>40,
        'max_bug'=>200,
        'min_task'=>50,
        'max_task'=>100]
];
